name: 03- workflow-runners

on: push

jobs:
     ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
           - name: show OS
             run: |
                echo: "This job us running on Ubuntu runner"
                echo: "Runner OS: $RUNNER_OS"
